services:
  - type: web
    name: safecode-web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
    autoDeploy: true
    healthCheckPath: /api/health
